# Generated by Django 4.1.7 on 2023-03-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_normal_remove_items_categories_delete_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gravy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravysabzi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nasta', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mithai', models.CharField(max_length=200)),
            ],
        ),
    ]
