# Generated by Django 4.1.7 on 2023-03-11 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_gravy_snacks_sweets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gravy',
        ),
        migrations.DeleteModel(
            name='Snacks',
        ),
        migrations.DeleteModel(
            name='Sweets',
        ),
    ]
