# Generated by Django 4.1.7 on 2023-03-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_gravy_delete_snacks_delete_sweets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gravy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravy', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snacks', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sweets', models.CharField(max_length=200)),
            ],
        ),
    ]
