# Generated by Django 4.1.7 on 2023-03-12 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_gravy_snacks_sweets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normal',
            old_name='fullname',
            new_name='normal',
        ),
    ]
