# Generated by Django 4.1.7 on 2023-03-12 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_fullname_normal_normal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normal',
            old_name='normal',
            new_name='fullname',
        ),
    ]
