# Generated by Django 4.1.7 on 2023-03-16 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post',
        ),
    ]
