# Generated by Django 4.1.7 on 2023-03-17 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0013_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='gravy',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gravyu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='normal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normalu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='snacks',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snacksu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sweets',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sweetsu', to=settings.AUTH_USER_MODEL),
        ),
    ]
