# Generated by Django 4.1.7 on 2023-03-18 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0015_remove_normal_user_normal_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gravy',
            name='user',
        ),
        migrations.RemoveField(
            model_name='snacks',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sweets',
            name='user',
        ),
        migrations.AddField(
            model_name='gravy',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='snacks',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sweets',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
