# Generated by Django 4.1.7 on 2023-03-18 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0017_menuitem_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='day2',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='item2',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='meal2',
            new_name='meal',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment_for_post',
        ),
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
