# Generated by Django 4.1.7 on 2023-03-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_gravy_gravy_alter_normal_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gravy',
            name='gravy',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='normal',
            name='fullname',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='snacks',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sweets',
            name='sweets',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
