# Generated by Django 4.1.7 on 2023-03-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_gravy_gravy_alter_normal_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='item',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='item1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='item2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='item3',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='item4',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
