# Generated by Django 4.1.7 on 2023-03-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_menuitem_item_menuitem_item1_menuitem_item2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='item1',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='item2',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='item3',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='item4',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='item',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
