# Generated by Django 4.1.7 on 2023-03-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_menuitem_item1_remove_menuitem_item2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='no_of_model',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
