# Generated by Django 4.1.7 on 2023-03-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_menuitem_no_of_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='no_of_model',
            field=models.IntegerField(null=True),
        ),
    ]
