# Generated by Django 4.1.7 on 2023-03-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_menuitem_no_of_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='no_of_model',
        ),
    ]
