# Generated by Django 4.1.7 on 2023-03-22 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_menuitem_no_of_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_chart', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='no_of_model',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menuname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.menuname'),
        ),
    ]
